---
- name: base
  import_tasks: base.yml

- name: config
  import_tasks: config.yml

- name: Create faucet account
  import_tasks: faucet.yml
  when: faucet_enabled | default(false) | bool

## Useful when we have the genesis file or url
# - name: join
#   import_tasks: join.yml
#   when: genesis_file is defined or genesis_url is defined

## Might be useful when connecting to apis
# - name: setup APIs
#   import_tasks: apis.yml

- include_role:
    name: faucet
  when: faucet_enabled | default(false) | bool

- name: setup systemd services
  import_tasks: services.yml

- name: Rebooting the machine
  include_role:
    name: reboot
  when: reboot | default(false) | bool
  tags:
    - reboot
