---
- name: Running the {{ chain_id }} chain
  shell: |
    export PATH=$PATH:$HOME/go/bin
    mkdir -p {{chain_home}}/logs
    {{ chain_bin }} start --log_level debug --pruning nothing --grpc.address :10192 --home {{ chain_home }} > {{chain_home}}/logs/chain.log 2>&1 &
  async: 10
  poll: 5
  become: yes
  ignore_errors: true
